[refactor] Improve typing
Mypy 1.20.0 had an obnoxious bug resulting in hundreds of errors such
as:

    pdf.py:161: error: Argument 1 to "__init__" of "SQLiteIndexMountSource"
    has incompatible type "**dict[str, Any | str | None]"; expected "int"  [arg-type]

1.20.1 seems to have fixed this, but only after I have lost hours trying
to fix this with TypedDict and typing.Unpack, which does not work for
Python 3.10. Deplorable.