[build] Avoid test requirements updating botocore to some incompatible version on Python 3.9
Fixes this error in the S3 regression tests:

      File "/site-packages/aiobotocore/session.py", line 243, in _create_client
        client = await client_creator.create_client(
      File "/site-packages/aiobotocore/client.py", line 88, in create_client
        client_args = await self._get_client_args(
      File "/site-packages/aiobotocore/client.py", line 301, in _get_client_args
        return await args_creator.get_client_args(
      File "/site-packages/aiobotocore/args.py", line 114, in get_client_args
        ruleset_resolver = self._build_endpoint_resolver(
      File "/site-packages/aiobotocore/args.py", line 184, in _build_endpoint_resolver
        resolver_builtins = self.compute_endpoint_resolver_builtin_defaults(
    TypeError: compute_endpoint_resolver_builtin_defaults()
               missing 1 required positional argument: 's3_disable_express_session_auth'

Probably introduced by this commit:
https://github.com/boto/botocore/commit/731a4dcfed0858fd519175b909ca3138e4715d1c